export const NEXT_MONTH = 'NEXT_MONTH';
export const PREV_MONTH = 'PREV_MONTH';
export const ASSIGN_ACTIVE_DAY = 'ASSIGN_ACTIVE_DAY';
export const UPDATE_DAYS_IN_MONTH = 'UPDATE_DAYS_IN_MONTH';
export const GO_TODAY = 'GO_TODAY';
export const GO_TO_MONTHS = 'GO_TO_MONTHS';
export const NEXT_YEAR = 'NEXT_YEAR';
export const PREV_YEAR = 'PREV_YEAR';
export const DISPLAY_MONTH ='DISPLAY_MONTH';
export const DISPLAY_DAYS = 'DISPLAY_DAYS';
export const DISPLAY_YEARS = 'DISPLAY_YEARS';
export const CHANGE_YEAR = 'CHANGE_YEAR';


export const SAVE_VALUE_EVENT = 'SAVE_VALUE_EVENT';
export const SAVE_TIME_EVENT = 'SAVE_TIME_EVENT';
export const PUSH_NEW_EVENT = 'PUSH_NEW_EVENT';
export const DISPLAY_CREATE_EVENT = 'DISPLAY_CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const DEFINE_EDITABLE_EVENT = 'DEFINE_EDITABLE_EVENT';
export const RESET_SELECTED_EVENT = 'RESET_SELECTED_EVENT';
export const REMEMBER_PRIMARY_TEXT = 'REMEMBER_PRIMARY_TEXT';
export const CACHE_EDITABLE_EVENT_TEXT = 'CACHE_EDITABLE_EVENT_TEXT';
export const SAVE_CHANGED_EVENT = 'SAVE_CHANGED_EVENT';
export const RECORD_ERROR = 'RECORD_ERROR';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const GO_TO_NEXT_DAY = 'GO_TO_NEXT_DAY';
export const GO_TO_PREV_DAY = 'GO_TO_PREV_DAY';
export const DISPLAY_CALENDAR_AND_REMEMBER_SELECTED_DAY = 'DISPLAY_CALENDAR_AND_REMEMBER_SELECTED_DAY';
export const UPDATE_NEXT_DISPLAY_AND_SELECTED_DATE = 'UPDATE_NEXT_DISPLAY_AND_SELECTED_DATE';
export const TEST_ADD_ANY_EVENTS = 'TEST_ADD_ANY_EVENTS';
export const UPDATE_SELECTED_DATE = 'UPDATE_SELECTED_DATE';
export const DISPLAY_CALENDAR = 'DISPLAY_CALENDAR';
export const DISPLAY_SHOW_EVENTS = 'DISPLAY_SHOW_EVENTS';
export const FETCH_EVENTS = 'FETCH_EVENTS';


export const SING_IN = 'SING_IN';
export const SING_OUT = 'SING_OUT';
export const ASSIGN_VALIDITY = 'ASSIGN_VALIDITY';
export const SET_IS_ERROR_MESSAGE = 'SET_IS_ERROR_MESSAGE';
export const ON_CHANGE_LOGIN_VALUE = 'ON_CHANGE_INPUT_VALUE';
export const ON_CHANGE_PASSWORD_VALUE = 'ON_CHANGE_PASSWORD_VALUE';