export const NEXT_MONTH = 'NEXT_MONTH';
export const PREV_MONTH = 'PREV_MONTH';
export const ASSIGN_ACTIVE_DAY = 'ASSIGN_ACTIVE_DAY';
export const UPDATE_DAYS_IN_MONTH = 'UPDATE_DAYS_IN_MONTH';
export const GO_TODAY = 'GO_TODAY';
export const GO_TO_MONTH = 'GO_TO_MONTH';
export const NEXT_YEAR = 'NEXT_YEAR';
export const PREV_YEAR = 'PREV_YEAR';
export const DISPLAY_MONTH ='DISPLAY_MONTH'
export const DISPLAY_DAYS = 'DISPLAY_DAYS'