export const SING_IN = 'SING_IN';
export const SING_OUT = 'SING_OUT';
export const ASSIGN_VALIDITY = 'ASSIGN_VALIDITY';
export const SET_IS_ERROR_MESSAGE = 'SET_IS_ERROR_MESSAGE';
export const ON_CHANGE_LOGIN_VALUE = 'ON_CHANGE_INPUT_VALUE';
export const ON_CHANGE_PASSWORD_VALUE = 'ON_CHANGE_PASSWORD_VALUE';